### ISSUE TITLE
[Feature Request] API Support

### ISSUE THREAD

**Issue by FunnyPocketBook** [Danil0v3s/CleanMeter#1]
Hi!

Thanks for this neat little program.

It would be great if the software could offer an API to expose performance data. The use case I have in mind is to store the data in a timeseries DB (e.g. Prometheus, InfluxDB), such that the history of the performance metrics can be displayed (e.g. Grafana)

**Comment by Danil0v3s** [comment]
Will look into it!

**Comment by ewenlau** [comment]
Shouldn't the data be exported at the MSI Afterburner level and not here?

**Comment by FunnyPocketBook** [comment]
You can, but then you need another program to run that. If you do it here, you have it all in one

**Comment by Danil0v3s** [comment]
> Hi!
> 
> Thanks for this neat little program.
> 
> It would be great if the software could offer an API to expose performance data. The use case I have in mind is to store the data in a timeseries DB (e.g. Prometheus, InfluxDB), such that the history of the performance metrics can be displayed (e.g. Grafana)

Hey, as of the newest beta release we have our own metrics process and that process creates a TCP Socket at 0.0.0.0:31337, it writes byte per byte so it's cheaper than serializing jsons and such. If you're comfortable with that you can try it out. [This](https://github.com/Danil0v3s/CleanMeter/blob/main/ConsoleApp1/Program.cs) shows a test connection in c#, and [this](https://github.com/Danil0v3s/CleanMeter/blob/main/core/native/src/main/kotlin/app/cleanmeter/core/os/hardwaremonitor/HardwareMonitorReader.kt#L51) is how I read the streams
