### ISSUE TITLE
Multiple instances are able to launch and overlay on top of each other

### ISSUE THREAD

**Issue by electricalastro** [Danil0v3s/CleanMeter#10]
If the program is already running, relaunching it starts another instance and overlays on top of the other. New instance shouldn't launch if one is already running.

**Comment by Danil0v3s** [comment]
Will look into it

**Comment by Danil0v3s** [comment]
> If the program is already running, relaunching it starts another instance and overlays on top of the other. New instance shouldn't launch if one is already running.

I've fixed it and a bunch more issues on the upcoming 1.0.0, the [beta1 ](https://github.com/Danil0v3s/CleanMeter/releases/tag/1.0.0.beta-1) is available in the meantime if you'd like to try it out
