### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by tokpig** [Danil0v3s/CleanMeter#12]
![image](https://github.com/user-attachments/assets/49c6302c-ab89-40ce-961e-36a6e9fbc7bf)
刚才下载安装就提示这个，确认后自动退出。

**Comment by dxhuii** [comment]
我也报了这个错误

**Comment by IraXu** [comment]
请先确保MSI Afterburner软件已经启动....

**Comment by Danil0v3s** [comment]
Hey, thanks for opening an issue. Please make sure you read the readme before getting started. It says you must have MSI Afterburner running
