### ISSUE TITLE
℃ display error

### ISSUE THREAD

**Issue by shoucandanghehe** [Danil0v3s/CleanMeter#19]
![image](https://github.com/user-attachments/assets/3ab3839e-35fc-4dce-8474-9bd7d3db7168)
Should I install any fonts?

system version: Windows11 23H2 22631.4317
system language: Chinese

**Comment by Danil0v3s** [comment]
> ![image](https://private-user-images.githubusercontent.com/51957264/380423183-3ab3839e-35fc-4dce-8474-9bd7d3db7168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTAwMTAsIm5iZiI6MTcyOTk0OTcxMCwicGF0aCI6Ii81MTk1NzI2NC8zODA0MjMxODMtM2FiMzgzOWUtMzVmYy00ZGNlLTg0NzQtOWJkN2QzZGI3MTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDEzMzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYzFjY2UzN2M0NzM0MzIxNDliODQzYzc5YzI5YTQyZDRiYTMwYmYwMDJlMzdlOTU3ODAzYWU5NGYzMThkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q93lgzIRMSWFX8ZnoeV3K14rFo-GfwSZJaAvX7dNLFU) Should I install any fonts?
> 
> system version: Windows11 23H2 22631.4317 system language: Chinese

Hey, I'm sorry I don't have the Chinese charset installed. The conversion I use is `ISO_8859_1`/`ISO-LATIN-1` (ISO Latin Alphabet). Could you try to install that charset and let me know if it works for you? Otherwise I might have to look for other solutions

**Comment by shoucandanghehe** [comment]
```python
>>> "℃".encode('gbk').decode('ISO_8859_1')
'¡æ'
```
It should be an encoding problem, but the Windows default encoding is determined by the display language.
So I can't change it.

**Comment by Danil0v3s** [comment]
> ```python
> >>> "℃".encode('gbk').decode('ISO_8859_1')
> '¡æ'
> ```
> 
> It should be an encoding problem, but the Windows default encoding is determined by the display language. So I can't change it.

Would UTF-8 work for you?

**Comment by shoucandanghehe** [comment]
> Would UTF-8 work for you?

no, I think hwinfo uses the system encoding, which is `gbk` for me
