### ISSUE TITLE
The app crashed the moment i switched to custom position and it no longer works now

### ISSUE THREAD

**Issue by staticshock129** [Danil0v3s/CleanMeter#23]

**Comment by Danil0v3s** [comment]
Hey @staticshock129 with absolutely no description provided it's a bit hard to provide a solution.

Anyways, I'll make a tool to reset the settings

**Comment by staticshock129** [comment]
oh sorry even i felt i was unreasonable
![Screenshot 2024-10-27 191316](https://github.com/user-attachments/assets/05ddf2af-cc8a-40f4-b173-50a61a16c93d)
once i chose the custom position it instantly crashed and kept me showing me this error everytime i opened it before automatically crashing again leaving me no chance to change it back

**Comment by staticshock129** [comment]
> Hey @staticshock129 with absolutely no description provided it's a bit hard to provide a solution.
> 
> Anyways, I'll make a tool to reset the settings



> oh sorry even i felt i was unreasonable
![Screenshot 2024-10-27 191316](https://github.com/user-attachments/assets/6cc70059-99b7-43df-9260-cc54fbcc57ce)

once i chose the custom position it instantly crashed and kept me showing me this error everytime i opened it before automatically crashing again leaving me no chance to change it back

**Comment by Danil0v3s** [comment]
> > Hey @staticshock129 with absolutely no description provided it's a bit hard to provide a solution.
> > Anyways, I'll make a tool to reset the settings
> 
> > oh sorry even i felt i was unreasonable
> > ![Screenshot 2024-10-27 191316](https://private-user-images.githubusercontent.com/115744282/380513239-6cc70059-99b7-43df-9260-cc54fbcc57ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTExMzMsIm5iZiI6MTczMDA1MDgzMywicGF0aCI6Ii8xMTU3NDQyODIvMzgwNTEzMjM5LTZjYzcwMDU5LTk5YjctNDNkZi05MjYwLWNjNTRmYmNjNTdjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxNzQwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmM0N2RmMTFlMWQ1NjJkM2MwYzdkYTJmODUyMTVlOTZiNjczYjgwMmYxMGI0ZjViNzNjNzQ3ZjY3MjUyZWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-YDP7q-rJ5079WLN0dD6CW6Q4HE_XkXGSadHrPrayTM)
> 
> once i chose the custom position it instantly crashed and kept me showing me this error everytime i opened it before automatically crashing again leaving me no chance to change it back

Can you check if there's a .log file please? The file is called `hs_err_pid<some numbers>.log`

**Comment by staticshock129** [comment]
Those are the two I found
[hs_err_pid27220.log](https://github.com/user-attachments/files/17535052
[hs_err_pid16980.log](https://github.com/user-attachments/files/17535053/hs_err_pid16980.log)
/hs_err_pid27220.log)

**Comment by staticshock129** [comment]
> > > Hey @staticshock129 with absolutely no description provided it's a bit hard to provide a solution.
> > > Anyways, I'll make a tool to reset the settings
> > 
> > 
> > > oh sorry even i felt i was unreasonable
> > > ![Screenshot 2024-10-27 191316](https://private-user-images.githubusercontent.com/115744282/380513239-6cc70059-99b7-43df-9260-cc54fbcc57ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTExMzMsIm5iZiI6MTczMDA1MDgzMywicGF0aCI6Ii8xMTU3NDQyODIvMzgwNTEzMjM5LTZjYzcwMDU5LTk5YjctNDNkZi05MjYwLWNjNTRmYmNjNTdjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxNzQwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmM0N2RmMTFlMWQ1NjJkM2MwYzdkYTJmODUyMTVlOTZiNjczYjgwMmYxMGI0ZjViNzNjNzQ3ZjY3MjUyZWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-YDP7q-rJ5079WLN0dD6CW6Q4HE_XkXGSadHrPrayTM)
> > 
> > 
> > once i chose the custom position it instantly crashed and kept me showing me this error everytime i opened it before automatically crashing again leaving me no chance to change it back
> 
> Can you check if there's a .log file please? The file is called `hs_err_pid<some numbers>.log` eg `hs_err_pid10336.log`


Those are the two I found
[hs_err_pid16980.log](https://github.com/user-attachments/files/17535057/hs_err_pid16980.log)
[hs_err_pid27220.log](https://github.com/user-attachments/files/17535056/hs_err_pid27220.log)

**Comment by staticshock129** [comment]
> > > > > Hey @staticshock129 with absolutely no description provided it's a bit hard to provide a solution.
> > 
> > 
> > > > > Anyways, I'll make a tool to reset the settings
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > oh sorry even i felt i was unreasonable
> > 
> > 
> > > > > ![Screenshot 2024-10-27 191316](https://private-user-images.githubusercontent.com/115744282/380513239-6cc70059-99b7-43df-9260-cc54fbcc57ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTExMzMsIm5iZiI6MTczMDA1MDgzMywicGF0aCI6Ii8xMTU3NDQyODIvMzgwNTEzMjM5LTZjYzcwMDU5LTk5YjctNDNkZi05MjYwLWNjNTRmYmNjNTdjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxNzQwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmM0N2RmMTFlMWQ1NjJkM2MwYzdkYTJmODUyMTVlOTZiNjczYjgwMmYxMGI0ZjViNzNjNzQ3ZjY3MjUyZWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-YDP7q-rJ5079WLN0dD6CW6Q4HE_XkXGSadHrPrayTM)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > once i chose the custom position it instantly crashed and kept me showing me this error everytime i opened it before automatically crashing again leaving me no chance to change it back
> > 
> > 
> > > 
> > 
> > 
> > > Can you check if there's a .log file please? The file is called `hs_err_pid<some numbers>.log` eg `hs_err_pid10336.log`
> > 
> > 
> > Those are the two I found
> > [hs_err_pid16980.log](https://github.com/user-attachments/files/17535057/hs_err_pid16980.log)
> > [hs_err_pid27220.log](https://github.com/user-attachments/files/17535056/hs_err_pid27220.log)
> 
> These are from Minecraft unfortunately 😕

Well, that's unexpected 😅
sorry i can't find anything else tho

**Comment by Danil0v3s** [comment]
> > > > > > Hey @staticshock129 with absolutely no description provided it's a bit hard to provide a solution.
> > > 
> > > 
> > > > > > Anyways, I'll make a tool to reset the settings
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > oh sorry even i felt i was unreasonable
> > > 
> > > 
> > > > > > ![Screenshot 2024-10-27 191316](https://private-user-images.githubusercontent.com/115744282/380513239-6cc70059-99b7-43df-9260-cc54fbcc57ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTExMzMsIm5iZiI6MTczMDA1MDgzMywicGF0aCI6Ii8xMTU3NDQyODIvMzgwNTEzMjM5LTZjYzcwMDU5LTk5YjctNDNkZi05MjYwLWNjNTRmYmNjNTdjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxNzQwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmM0N2RmMTFlMWQ1NjJkM2MwYzdkYTJmODUyMTVlOTZiNjczYjgwMmYxMGI0ZjViNzNjNzQ3ZjY3MjUyZWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-YDP7q-rJ5079WLN0dD6CW6Q4HE_XkXGSadHrPrayTM)
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > once i chose the custom position it instantly crashed and kept me showing me this error everytime i opened it before automatically crashing again leaving me no chance to change it back
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Can you check if there's a .log file please? The file is called `hs_err_pid<some numbers>.log` eg `hs_err_pid10336.log`
> > > 
> > > 
> > > Those are the two I found
> > > [hs_err_pid16980.log](https://github.com/user-attachments/files/17535057/hs_err_pid16980.log)
> > > [hs_err_pid27220.log](https://github.com/user-attachments/files/17535056/hs_err_pid27220.log)
> > 
> > 
> > These are from Minecraft unfortunately 😕
> 
> Well, that's unexpected 😅 sorry i can't find anything else tho

Hey, I don't see any better way around this other than sending you this new build which manually sets the location of that log file. Can you try running it and let me know? https://github.com/Danil0v3s/CleanMeter/releases/tag/0.0.5.beta2
