### ISSUE TITLE
Start with Windows does not ask for permission (and does not work)

### ISSUE THREAD

**Issue by OsaCode** [Danil0v3s/CleanMeter#27]
How to reproduce :
1. Run Clean Meter.exe
2. Go to settings
3. Tick "Start with Windows"

I have tried to solve it by running it as administrator but it displayed "Can not read the info" instead of the app.

**Comment by Danil0v3s** [comment]
I'll take a look on this, several people reported it isn't working

**Comment by Danil0v3s** [comment]
[Latest release (0.0.7)](https://github.com/Danil0v3s/CleanMeter/releases/latest) should take care of it. Please re-open if the issue persists
