### ISSUE TITLE
FPS shows 0 in game

### ISSUE THREAD

**Issue by OsaCode** [Danil0v3s/CleanMeter#28]
![image](https://github.com/user-attachments/assets/e029a451-c702-4cd1-9231-fa79746ab689)
HWInfo is running, the Shared memory is enabled and all other informations work (even frame time graph)

**Comment by Danil0v3s** [comment]
> ![image](https://private-user-images.githubusercontent.com/46417195/380765412-e029a451-c702-4cd1-9231-fa79746ab689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzAzNTcsIm5iZiI6MTczMDEzMDA1NywicGF0aCI6Ii80NjQxNzE5NS8zODA3NjU0MTItZTAyOWE0NTEtYzcwMi00Y2QxLTkyMzEtZmE3OTc0NmFiNjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDE1NDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNzBhODljM2VjNTM5ZjcwYmEyYjM5ZGEyYWQ3NTVlYmIwZjY5ZDU5NWUxZjg2ZWRiMjMwOWIwYWE5MTM2NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tA3d4ZdtWjfUYLUZbn60Pu4CMDF3lWeUPuve8llv5WQ) HWInfo is running, the Shared memory is enabled and all other informations work (even frame time graph)

Hey, if you open the HWInfo sensors window what does it show under `PresentMon`?

**Comment by OsaCode** [comment]
It shows the correct number of fps 
![image](https://github.com/user-attachments/assets/04a7cfbb-7e6b-4fe5-b53f-5c43042b4ec3)

**Comment by Danil0v3s** [comment]
Which version are you using? Could you try the [0.0.5.beta.2](https://github.com/Danil0v3s/CleanMeter/releases/tag/0.0.5.beta2) and see if it's fixed please?

**Comment by OsaCode** [comment]
I was on release
It works now on 0.0.5.beta.2 although I had to restart Hwinfo manually because it showed " no info " on first start.
