### ISSUE TITLE
Application window size is not fully displayed

### ISSUE THREAD

**Issue by PearNoDec** [Danil0v3s/CleanMeter#29]
I am a laptop, the screen is not very large, when opening software, the lower part does not show up, I drag everything to the top, but my screen cannot accommodate it either, I hope it can support scaling adaptively based on the screen height

For example, the following shows.

My Windows computer says "Unable to read data..."

![Demo](https://github.com/user-attachments/assets/246d9490-5546-4ff2-bd9e-6f92ac834b33)

**Comment by PearNoDec** [comment]
> I am a laptop, the screen is not very large, when opening software, the lower part does not show up, I drag everything to the top, but my screen cannot accommodate it either, I hope it can support scaling adaptively based on the screen height

![Uploading PixPin_2024-10-30_09-15-50.png…]()

**Comment by Danil0v3s** [comment]
Will make the window height smaller

**Comment by Danil0v3s** [comment]
> I am a laptop, the screen is not very large, when opening software, the lower part does not show up, I drag everything to the top, but my screen cannot accommodate it either, I hope it can support scaling adaptively based on the screen height
> 
> 
> 
> For example, the following shows.
> 
> 
> 
> My Windows computer says "Unable to read data..."
> 
> 
> 
> ![Demo](https://github.com/user-attachments/assets/246d9490-5546-4ff2-bd9e-6f92ac834b33)

Could you try the newest release and let me know? I've made the height smaller

**Comment by PearNoDec** [comment]
I found that the problem still exists, maybe it would be better if users could customize the window resizing size
![show](https://github.com/user-attachments/assets/3e893900-7c46-466e-8892-d4a606c98b0e)

**Comment by Danil0v3s** [comment]
> I found that the problem still exists, maybe it would be better if users could customize the window resizing size ![show](https://private-user-images.githubusercontent.com/125916617/387080999-3e893900-7c46-466e-8892-d4a606c98b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NzQ0MTAsIm5iZiI6MTczNTY3NDExMCwicGF0aCI6Ii8xMjU5MTY2MTcvMzg3MDgwOTk5LTNlODkzOTAwLTdjNDYtNDY2ZS04ODkyLWQ0YTYwNmM5OGIwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxOTQxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzQ4ZmI3ZDI2MzE3NTg5Y2Q0ODFmOTBhOWE2YzAzMjc1NGJmOWQxYTA4MjY4ODg5YzYzZTE2NDE1YjRmMTk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vy1DzbVvBqMKpFueJjPrxZaZqVo1UeopMcVpi2YBSbM)

#50 should fix this issue, we are now calculating the size to be within the safe bounds. Should be available with 1.0 in a couple of days
