### ISSUE TITLE
[Feature Request] Degrees Fahrenheit 

### ISSUE THREAD

**Issue by zedja8fold** [Danil0v3s/CleanMeter#3]

**Comment by zedja8fold** [comment]
Upon second glance, my temp readouts actually are giving me Fahrenheit because that's what I have Afterburner set to. However, they are still displayed with the unit for Celsius.

**Comment by Danil0v3s** [comment]
Hey, thanks for letting me know! Will make sure it respects the unit coming from afterburner

**Comment by Danil0v3s** [comment]
Should be fixed with #11
