### ISSUE TITLE
FPS stuck at 0

### ISSUE THREAD

**Issue by Mysterymau0521** [Danil0v3s/CleanMeter#31]
My FPS shows that it is 0 but all of the other sensors. HWinfo shows that the framerate sensor is running but is not populating on Clean Meter

**Comment by Danil0v3s** [comment]
> My FPS shows that it is 0 but all of the other sensors. HWinfo shows that the framerate sensor is running but is not populating on Clean Meter

Which version are you using? Could you try the [0.0.5.beta.2](https://github.com/Danil0v3s/CleanMeter/releases/tag/0.0.5.beta2) and see if it's fixed please?

**Comment by Mysterymau0521** [comment]
That fixed it. Thank you!
