### ISSUE TITLE
[Feature Request] HWInfo64 plugin rather than shared memory access

### ISSUE THREAD

**Issue by Pink-skul** [Danil0v3s/CleanMeter#32]
Hey there,

I wanted to use this with HWInfo however the need to use the shared access memory feature is expensive and exhausting having to turn on the feature every 12 hours.

I saw a thread on reddit that people have been making use of the HWinfo plugin feature of some sort that avoids this issue and the need to use shared access memory.

Any way you can look into that?

**Comment by Danil0v3s** [comment]
I've looked into that in the past and it requires user setup and I didn't have a good experience with users having to setup things (People can't seem to read nowadays).

I've done something else in the [latest release (0.0.7)](https://github.com/Danil0v3s/CleanMeter/releases/tag/0.0.7) though. If you uninstall HWiNFO, CleanMeter will take care of launching a portable version of it and manage the 12h timer by relaunching the process in case it cannot read info for more than 5 seconds.
