### ISSUE TITLE
[BUG] Hotkey enabling defaults position in main monitor

### ISSUE THREAD

**Issue by Pink-skul** [Danil0v3s/CleanMeter#36]
Hi! As mentioned in my other issue logged, will donate when I can :)
A bug I have notice in the 0.0.7 release is that when using the hotkey to turn the meter on/off, it reverts to the default position i.e. main monitor, top right corner no matter the setting of the position and display selected

![image](https://github.com/user-attachments/assets/080ef3a9-8bff-4c48-8449-dc7e7ed9849f)

**Comment by Danil0v3s** [comment]
> Hi! As mentioned in my other issue logged, will donate when I can :)
> 
> A bug I have notice in the 0.0.7 release is that when using the hotkey to turn the meter on/off, it reverts to the default position i.e. main monitor, top right corner no matter the setting of the position and display selected
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/080ef3a9-8bff-4c48-8449-dc7e7ed9849f)
> 
> 

Will look into that 🤔

**Comment by Danil0v3s** [comment]
> Hi! As mentioned in my other issue logged, will donate when I can :)
> 
> A bug I have notice in the 0.0.7 release is that when using the hotkey to turn the meter on/off, it reverts to the default position i.e. main monitor, top right corner no matter the setting of the position and display selected
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/080ef3a9-8bff-4c48-8449-dc7e7ed9849f)
> 
> 

Hello, that seem to have been fixed at the 0.0.8 release, could you try it out?
