### ISSUE TITLE
Strange white bar appearing behind the program ui

### ISSUE THREAD

**Issue by KynPrism** [Danil0v3s/CleanMeter#38]
Whenever the usage panel (CPU, GPU, RAM, etc.) is displayed, a strange white bar also appears on the Windows interface. It seems to be part of the program’s UI but shouldn’t be there.

![Captura de tela 2024-11-17 193120](https://github.com/user-attachments/assets/7d9bdc8e-66fa-41fb-958e-1ddf8e658879)

I have an ultrawide monitor (i dont know if it correlates)
This happens every time I open the panel, and it doesn’t go away unless I close the program.

**Comment by Danil0v3s** [comment]
> Whenever the usage panel (CPU, GPU, RAM, etc.) is displayed, a strange white bar also appears on the Windows interface. It seems to be part of the program’s UI but shouldn’t be there.
> 
> ![Captura de tela 2024-11-17 193120](https://private-user-images.githubusercontent.com/134095568/387010795-7d9bdc8e-66fa-41fb-958e-1ddf8e658879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjQ0MzQsIm5iZiI6MTczMTkyNDEzNCwicGF0aCI6Ii8xMzQwOTU1NjgvMzg3MDEwNzk1LTdkOWJkYzhlLTY2ZmEtNDFmYi05NThlLTFkZGY4ZTY1ODg3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxMDAyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWFmYmY3YWI0OWYyNWQ2YjVkZGMzMGFiOTJkNDJjYWU0MDcyOWQ3NzY3MTVjMTZhMjBjYTU2MDRjZjRmMmU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EbL8-vNax5fzKEPxZDrZbwY3agmw0BXct0kWYST-P60)
> 
> I have an ultrawide monitor (i dont know if it correlates) This happens every time I open the panel, and it doesn’t go away unless I close the program.

This is a first, have you tried changing back to horizontal to see if the white background disappears? Also, which windows version are you using?

**Comment by Danil0v3s** [comment]
> Whenever the usage panel (CPU, GPU, RAM, etc.) is displayed, a strange white bar also appears on the Windows interface. It seems to be part of the program’s UI but shouldn’t be there.
> 
> ![Captura de tela 2024-11-17 193120](https://private-user-images.githubusercontent.com/134095568/387010795-7d9bdc8e-66fa-41fb-958e-1ddf8e658879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3Nzc2NDgsIm5iZiI6MTczMzc3NzM0OCwicGF0aCI6Ii8xMzQwOTU1NjgvMzg3MDEwNzk1LTdkOWJkYzhlLTY2ZmEtNDFmYi05NThlLTFkZGY4ZTY1ODg3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQyMDQ5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGViMDhlOTIzMWMyNDU3YjBkZjE4NjRiZTRmZTEwNGIyZGYxNjc3MDYyOWI0ZjE4YWQ3MTljNGUzMTI3M2E5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qJ55NKJULUZBe1pN8jj6SM75BNcg5yOTE6KjYstocUg)
> 
> I have an ultrawide monitor (i dont know if it correlates) This happens every time I open the panel, and it doesn’t go away unless I close the program.

There was a few other people that showed up on discord with that problem and they said rebooting the PC have worked for them. Anyways, we've released a new [1.0.0-beta1](https://github.com/Danil0v3s/CleanMeter/releases/tag/1.0.0.beta-1). Could you try it and let me know?
