### ISSUE TITLE
[Feature Request] Hotkey to Toggle On/Off

### ISSUE THREAD

**Issue by zedja8fold** [Danil0v3s/CleanMeter#4]

**Comment by Danil0v3s** [comment]
Currently considering a customisable key combo to toggle the overlay

**Comment by Danil0v3s** [comment]
@zedja8fold I've added basic support for it on c938f5dd5cf053d5c69219c5a8bc38e1953e99dc. Available at https://github.com/Danil0v3s/CleanMeter/releases/tag/0.0.3-beta.1
