### ISSUE TITLE
[BUG] CPU stats always show 1

### ISSUE THREAD

**Issue by xMrOVERLORDx** [Danil0v3s/CleanMeter#43]
Somehow the CPU info is the only one that isn't working for me, it always shows up as 1v or just 1. I've tested this in 3 games with windowed, borderless and fullscreen modes. No idea what the issue is here

Cpu- I5 13600KF

**Comment by Danil0v3s** [comment]
Did you configure the sensors correctly for the CPU? If it's showing 1v it means the sensor you selected is showing a voltage

**Comment by xMrOVERLORDx** [comment]
I was using the default values at first but couldn't find the correct values to use for temp and usage in the drop-down menu either
