### ISSUE TITLE
[Feature Request] Support Polling Intervals.

### ISSUE THREAD

**Issue by txj-xyz** [Danil0v3s/CleanMeter#45]
**Is your feature request related to a problem? Please describe.**
No, Just want to be able to adjust polling intervals properly.

**Describe the solution you'd like**
- Adjustment slider
- Perhaps custom range?

Assuming native implementation can be adjusted to load from deserialized data or static from somewhere init

https://github.com/Danil0v3s/CleanMeter/blob/86175e87e0403220e012f83d74ae9b15c7b46931/core/native/src/main/kotlin/app/cleanmeter/core/os/hwinfo/HwInfoReader.kt#L30

**Describe alternatives you've considered**
?

**Additional context**
no

**Comment by Danil0v3s** [comment]
Hey! Two things:

1. We're moving away from HWInfo/afterburner in the next version (beta available)
2. Faster polling would drain more resources, we could of course create an option to allow you to select whatever rate you'd like but that would need to have a big warning sign

**Comment by txj-xyz** [comment]
Any supported range would be nice :)

**Comment by Danil0v3s** [comment]
> Any supported range would be nice :)

Fixed with https://github.com/Danil0v3s/CleanMeter/pull/52, should be released with 1.0 in the next couple of days. In the meanwhile you can get the archive from https://github.com/Danil0v3s/CleanMeter/actions/runs/12552120404
