### ISSUE TITLE
Suggestions or ideas 

### ISSUE THREAD

**Issue by Obivxx** [Danil0v3s/CleanMeter#5]
I initially spoke to VioletMars on Reddit because I really liked the idea of a minimalist UI as many companies don't care about the User Experience it's nice to see you guys have picked this up and made it a reality. A few things should be considered regarding how customisable it can be for example allowing people to split up the bars, and a drag-and-drop feature so you can pick where you want it. Also allowing the application to choose which software the application is drawing the FPS reading from. maybe a pin and unpin feature you could try to get an application on the Windows store so you can link it like Crosshair X has done, to WIN + G so it's an overlay that you can disable at any time. Im not trying to overwhelm you guys, just ideas that Im thinking of and If you need more hands-on please let me know I love to support you in any way I can.

**Comment by Danil0v3s** [comment]
Hey, someone else mentioned over Reddit there's a couple other ways of rendering an overlay. So I might invest some time into it down the road.

There's a bunch of things we consider priority right now but these ideas will come in handy at some point in time!
