### ISSUE TITLE
no FPS readout + no way to get settings back up

### ISSUE THREAD

**Issue by SlowThaiZR** [Danil0v3s/CleanMeter#6]
downloaded, activated MSI afterburner and thought it had set it up, have GPU temp and load, CPU temp and load. no FPS counter, this is just at 0, also no way to get the configuation menu back up again?

**Comment by SlowThaiZR** [comment]
edit: enabling "framerate" in afterburner active monitoring graphs just means that it starts at 480fps, drops to 37fps then 0

**Comment by Danil0v3s** [comment]
Hey! The settings once you close go to the tray. Double click and it should come up again.

I'll add a confirmation that it's going to the tray

**Comment by SlowThaiZR** [comment]
hahaha yep found it, thanks! the logo looked kind of like the playstation buttons so i thought it was some controller software. thanks again this app is amazing!
