### ISSUE TITLE
Fatal Error - Force close and unresponsive toggle settings

### ISSUE THREAD

**Issue by jwsw1990** [Danil0v3s/CleanMeter#8]
[hs_err_pid4504.log](https://github.com/user-attachments/files/17462348/hs_err_pid4504.log)
[hs_err_pid8896.log](https://github.com/user-attachments/files/17462350/hs_err_pid8896.log)
[hs_err_pid10836.log](https://github.com/user-attachments/files/17462353/hs_err_pid10836.log)

Encounter forced closure after the meter went unresponsive. And I couldn't toggle the settings.

**Comment by mchinmay24** [comment]
> Hey, is this something you can reproduce easily?
> 
> Also I don't really know what's going on with that log but I see something about "privileged". Could you try executing as admin and see if the problem persists?

Same issue, and it's happens every time on launch, the window opens for a very brief moment and crashes almost instantly upon launch

**Comment by Danil0v3s** [comment]
Hey @jwsw1990 could you check above and let me know if it's the solution for your issue, please?
